version: '3.4'
services:
  turbo-geth.dnp.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v2020.10.03
    image: 'turbo-geth.dnp.dappnode.eth:0.1.0'
    restart: always
    volumes:
      - 'data:/root/.local/share/turbogeth'
    environment:
      - LMDB_MAPSIZE=2000GB
      - EXTRA_OPTS=''
volumes:
  data: {}
