version: '3.4'
services:
  turbo-geth.public.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: master
    image: 'turbo-geth.public.dappnode.eth:0.1.0'
    restart: always
    volumes:
      - 'data:/root/.local/share/turbogeth'
    environment:
      - LMDB_MAPSIZE=
volumes:
  data: {}
