version: "3.4"
services:
  tg:
    image: "tg.turbo-geth.dnp.dappnode.eth:0.1.0"
    build:
      context: tg
      args:
        UPSTREAM_VERSION: v2021.06.05
    ports:
      - "30303"
      - 30303/udp
    restart: unless-stopped
    volumes:
      - "data:/root/.local/share/turbogeth"
    environment:
      TURBO_GETH_EXTRA_OPTS: ""
  rpcdaemon:
    image: "rpcdaemon.turbo-geth.dnp.dappnode.eth:0.1.0"
    build:
      context: rpcdaemon
      args:
        UPSTREAM_VERSION: v2021.06.05
    environment:
      RPCDAEMON_EXTRA_OPTS: "--http.api=eth,debug,net,web3"
    restart: unless-stopped
volumes:
  data: {}
